const blogRouting = require('../services/blogService')
const categoryRouting = require('../services/admin/categoryService')
const loginService = require('../services/auth/loginService')
const registerService = require('../services/auth/registerService')
const userService = require('../services/userService')
const commentRouting = require('../services/commentService')

app.use('/register', registerService)
app.use('/login', loginService)
app.use('/blogs', blogRouting)
app.use('/account', userService)
app.use('/admin/category', categoryRouting)
app.use('/comment', commentRouting)